name: Build and Test
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker run
      uses: docker/build-push-action@v3
      with:
#         context: .
        build-args: nuget_api_key=${{ secrets.NUGET_API_KEY }}
        file: PazExt/Dockerfile
