name: Build and Test
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build . --build-arg nuget-api-key=${{ secrets.NUGET_API_KEY }}
