name: Build and Test
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore PazExt/Paze.Extensions/Paze.Extensions.csproj
    - name: Build
      run: dotnet build PazExt/Paze.Extensions/Paze.Extensions.csproj --configuration Release --no-restore