name: Build and Test
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker build
      run: docker build . --build-arg nuget-api-key=${{ secrets.NUGET_API_KEY }}
